import { useState, useEffect, useCallback } from 'react'
import { Box, Typography, Container, useMediaQuery, useTheme } from '@mui/material'
import { motion, AnimatePresence } from 'framer-motion'
import { Close } from '@mui/icons-material'

const VIDEO_EXTS = new Set(['mp4', 'webm', 'mov', 'ogg'])

interface GalleryItem {
  src: string
  type: 'image' | 'video'
}

const Gallery: React.FC = () => {
  const [items, setItems] = useState<GalleryItem[]>([])
  const [lightbox, setLightbox] = useState<string | null>(null)
  const base = import.meta.env.BASE_URL
  const theme = useTheme()
  const isSm = useMediaQuery(theme.breakpoints.up('sm'))
  const isMd = useMediaQuery(theme.breakpoints.up('md'))
  const isLg = useMediaQuery(theme.breakpoints.up('lg'))
  const numColumns = isLg ? 4 : isMd ? 3 : isSm ? 2 : 1

  // Distribute items left-to-right (row-first) into columns
  const columns = Array.from({ length: numColumns }, (_, col) =>
    items.filter((_, i) => i % numColumns === col)
  )

  const closeLightbox = useCallback(() => setLightbox(null), [])

  useEffect(() => {
    const handleKey = (e: KeyboardEvent) => { if (e.key === 'Escape') closeLightbox() }
    window.addEventListener('keydown', handleKey)
    return () => window.removeEventListener('keydown', handleKey)
  }, [closeLightbox])

  useEffect(() => {
    // gallery-manifest.json is auto-generated by the Vite plugin in vite.config.ts
    // from whatever files exist in public/gallery/ — no manual list needed.
    fetch(`${base}gallery-manifest.json`)
      .then(r => r.json())
      .then((files: string[]) => {
        const parsed: GalleryItem[] = files.map(f => {
          const ext = f.split('.').pop()?.toLowerCase() ?? ''
          return { src: `${base}gallery/${f}`, type: VIDEO_EXTS.has(ext) ? 'video' : 'image' }
        })
        // Videos always last
        parsed.sort((a, b) => (a.type === 'video' ? 1 : 0) - (b.type === 'video' ? 1 : 0))
        setItems(parsed)
      })
      .catch(() => setItems([]))
  }, [base])

  return (
    <Box sx={{ minHeight: '100vh', backgroundColor: '#0a192f', pt: '100px', pb: 8 }}>
      <Container maxWidth="xl">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <Box sx={{ textAlign: 'center', mb: 8, mt: 6 }}>
            <Typography
              variant="h6"
              sx={{
                color: '#64ffda',
                fontSize: '1.1rem',
                fontWeight: 500,
                mb: 1,
                letterSpacing: '0.1em',
                textTransform: 'uppercase',
              }}
            >
              gallery
            </Typography>
            <Typography
              variant="h2"
              sx={{
                fontSize: { xs: '2.5rem', md: '3rem' },
                fontWeight: 700,
                color: '#ccd6f6',
                display: 'inline-flex',
                alignItems: 'center',
                gap: 2,
                '&::before': {
                  content: '"✦"',
                  color: '#64ffda',
                  fontSize: '2rem',
                },
              }}
            >
              Professional Events
            </Typography>
            <Typography
              variant="body1"
              sx={{
                mt: 2,
                color: '#a8b2d1',
                fontSize: '1rem',
                maxWidth: 480,
                mx: 'auto',
                lineHeight: 1.7,
              }}
            >
              Conferences, hackathons, and moments worth remembering.
            </Typography>
          </Box>
        </motion.div>

        {/* Masonry Grid */}
        {items.length > 0 ? (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.6, delay: 0.2 }}
          >
            <Box sx={{ display: 'flex', gap: '16px', alignItems: 'flex-start' }}>
              {columns.map((col, colIdx) => (
                <Box key={colIdx} sx={{ flex: 1, display: 'flex', flexDirection: 'column', gap: '16px' }}>
                  {col.map((item) => {
                    // Global index for stagger delay
                    const globalIdx = items.indexOf(item)
                    return (
                      <motion.div
                        key={item.src}
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.5, delay: globalIdx * 0.04 }}
                      >
                        <Box
                          onClick={() => item.type === 'image' && setLightbox(item.src)}
                          sx={{
                            overflow: 'hidden',
                            borderRadius: '8px',
                            border: '1px solid rgba(100, 255, 218, 0.08)',
                            cursor: item.type === 'video' ? 'default' : 'zoom-in',
                            transition: 'all 0.35s ease',
                            '&:hover': {
                              border: '1px solid rgba(100, 255, 218, 0.4)',
                              boxShadow: '0 8px 32px rgba(100, 255, 218, 0.12)',
                              transform: 'translateY(-3px)',
                            },
                            '&:hover img': { transform: 'scale(1.03)' },
                          }}
                        >
                          {item.type === 'video' ? (
                            <Box
                              component="video"
                              src={item.src}
                              controls
                              playsInline
                              sx={{ width: '100%', height: 'auto', display: 'block' }}
                            />
                          ) : (
                            <Box
                              component="img"
                              src={item.src}
                              sx={{
                                width: '100%',
                                height: 'auto',
                                display: 'block',
                                transition: 'transform 0.35s ease',
                              }}
                            />
                          )}
                        </Box>
                      </motion.div>
                    )
                  })}
                </Box>
              ))}
            </Box>
          </motion.div>
        ) : (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.6, delay: 0.2 }}
          >
            <Box sx={{ textAlign: 'center', mt: 12 }}>
              <Typography variant="h6" sx={{ color: '#a8b2d1', fontWeight: 400 }}>
                Loading...
              </Typography>
            </Box>
          </motion.div>
        )}
      </Container>

      {/* Lightbox */}
      <AnimatePresence>
        {lightbox && (
          <motion.div
            key="lightbox-backdrop"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.25 }}
            onClick={closeLightbox}
            style={{
              position: 'fixed',
              inset: 0,
              backgroundColor: 'rgba(5, 15, 30, 0.85)',
              backdropFilter: 'blur(6px)',
              zIndex: 2000,
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              padding: '40px',
            }}
          >
            {/* Close button */}
            <Box
              onClick={closeLightbox}
              sx={{
                position: 'absolute',
                top: 24,
                right: 28,
                color: '#a8b2d1',
                cursor: 'pointer',
                transition: 'color 0.2s ease, transform 0.2s ease',
                '&:hover': { color: '#64ffda', transform: 'rotate(90deg)' },
              }}
            >
              <Close fontSize="large" />
            </Box>

            <motion.img
              key={lightbox}
              src={lightbox}
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.9 }}
              transition={{ duration: 0.3, ease: 'easeOut' }}
              onClick={(e) => e.stopPropagation()}
              style={{
                maxWidth: '82vw',
                maxHeight: '82vh',
                borderRadius: '10px',
                boxShadow: '0 24px 80px rgba(0,0,0,0.6)',
                objectFit: 'contain',
                cursor: 'default',
              }}
            />
          </motion.div>
        )}
      </AnimatePresence>
    </Box>
  )
}

export default Gallery
